spring:
  application:
    name: demo
  web:
    resources:
      add-mappings: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-paths: src/main/java
