spring:
  application:
    name: demo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/testdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: TestdbRoot

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    #    show-sql: true
    defer-datasource-initialization: false

    properties:
      hibernate:
        jdbc:
          batch_size: 10
          time_zone: Asia/Seoul
        order_inserts: true
        order_updates: true
        format_sql: true
        use_sql_comments: true

  sql:
    init:
      mode: never

  web:
    resources:
      add-mappings: false

#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: true
#      additional-paths: src/main/java
