@baseUrl=http://localhost:8080/api/members

### member list
GET {{baseUrl}}/

### member-regist
POST {{baseUrl}}
Content-Type: application/json

{
  "nickname": "guest",
  "email": "guest@email.com",
  "passwd": "xxxxxxxx",
  "bloodType": "O",
  "isActive": true
}

### member-info
GET {{baseUrl}}/5


### post-update
PUT {{baseUrl}}/5
Content-Type: application/json

{
  "id": 4,
  "nickname": "guestxx",
  "email": "guest@email.comxx",
  "passwd": "xxxxxxxx",
  "bloodType": "O",
  "isActive": false
}

### withdraw member
DELETE {{baseUrl}}/5
