@baseUrl=http://localhost:8080/api/members

### member list
GET {{baseUrl}}/

### member-regist
POST {{baseUrl}}
Content-Type: application/json

{
  "title": " ",
  "body": "body 1",
  "writer": "1"
}

### member-info
GET {{baseUrl}}/1


### post-update
PUT {{baseUrl}}/1
Content-Type: application/json

{
  "title": "title 1x",
  "body": "body 1xxx",
  "writer": "Hongxxx"
}

### post-remove
DELETE {{baseUrl}}/1
