@baseUrl=http://localhost:8080

### user list
GET {{baseUrl}}/users

### user-regist
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "xxx",
  "email": "hong@mail.com",
  "comail": "hong@hanabank.co",
  "tel": "010-12-5678"
}

### user-regist
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "Kim",
  "email": "kim@mail.com",
  "tel": "010-1234-5678"
}

### user-info
GET {{baseUrl}}/users/1


### user-update
PUT {{baseUrl}}/users/1
Content-Type: application/json

{
  "id": 0,
  "username": "Hongx",
  "email": "hongx@mail.com",
  "tel": "010-1234-5678"
}

### user-withdraw
DELETE {{baseUrl}}/users/1
