@baseUrl=http://localhost:8080

### user list
GET {{baseUrl}}/users

### user-info
GET {{baseUrl}}/users/1

### user-regist
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "Hong",
  "email": "hong@email.com",
  "tel": "010-1234-5678"
}

### user-update
PUT {{baseUrl}}/users/1

{
  "username": "Hong",
  "email": "hong@email.com",
  "tel": "010-1234-5678"
}

### user-withdraw
DELETE {{baseUrl}}/users/1
