@api=http://localhost:3000/api
# @api=https://dev.hana.com/api

### book list
GET {{api}}/books

### add book
POST {{api}}/books

{
  "title": "New book",
  "writer": "jade"
}

### get a book   fetch().then(res => res.json())
GET {{api}}/books/2

### patch a book
PATCH {{api}}/books/23

{
  "title": "New title",
  "writer": "jade"
}

### delete a book
DELETE {{api}}/books/2